version: "3.9"

services:
  #  PostgreSQL
  database-postgres:
    image: postgres:14
    container_name: postgres
    environment:
      - POSTGRES_DB=intership-db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
    ports:
      - 5432:5432

  #  Elasticsearch
  database-elasticsearch:
    image: elasticsearch:8.2.0
    container_name: elasticsearch
    environment:
      # Password for the 'elastic' user
      - ELASTIC_PASSWORD=admin
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - 9200:9200
      - 9300:9300