version: "3.9"

services:
  # Application
  internship:
    image: maxirage/internship
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
    - 8080:8080
    depends_on:
      - database-elasticsearch
      - database-postgres


  #  PostgreSQL
  database-postgres:
    image: postgres:14
    container_name: postgres
    restart: always
    environment:
      - POSTGRES_DB=intership-db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5433:5432

  #  Elasticsearch
  database-elasticsearch:
    image: elasticsearch:8.2.0
    container_name: elasticsearch
    restart: always
    environment:
      # Password for the 'elastic' user
      - ELASTIC_PASSWORD=admin
      - discovery.type=single-node
      - xpack.security.enabled=true
      - xpack.security.http.ssl.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - 9200:9200
      - 9300:9300
