version: "3.9"

services:
  database:
    image: postgres:14
    container_name: postgres
    environment:
      POSTGRES_DB: intership-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - 5432:5432