# Server
server:
  error:
    include-binding-errors: always
    include-message: always
    include-exception: true
  shutdown: graceful

spring:
  # PostgreSQL
  datasource:
    url: jdbc:postgresql://localhost:5432/intership-db
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: admin

  # JPA
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
    show-sql: true

  # Liquibase
  liquibase:
    change-log: classpath:liquibase/db.changelog_master.yaml
    url: jdbc:postgresql://localhost:5432/intership-db
    user: postgres
    password: admin

  # Elasticsearch
  elasticsearch:
    uris: localhost:9200
    connection-timeout: 3s
    socket-timeout: 60s
    username: elastic
    password: admin

  # Mail options
  mail:
    host: smtp.gmail.com
    port: 465
    username: fedagedu@gmail.com
    password:
    protocol: smtps
    properties:
      mail:
        smtp:
          auth: true
          connectiontimeout: 1000
          timeout: 1000
          writetimeout: 1000
          starttls:
            enable: true

  # Spring security configuration
jwt:
  header: Authorization
  secret: secret
  expiration: 604800
  
  #Spring Scheduler
job:
  timeForScheduler: 3600000
  
  # Registration options
token:
  minutes-to-expire: 60

  #JDoodle Api
jdoodle:
  compiler-url: https://api.jdoodle.com/v1/execute
  client-id: 6cb34a262060d9b524aa0eb32ed6faa9
  client-secret: 8e923e7fbd6ea3f8a500085bb4354ca807a318258fc6423d249f9fa4f19d825d